### ISSUE TITLE
PBR does not work with model loaded from OBJ format in 50% cases

### ISSUE THREAD

**Issue by jacobwyn** [viromedia/virocore#52]
I am trying to render simple obj model in with PBR [asset.zip](https://github.com/viromedia/virocore/files/1819854/model.zip)

another assets https://poly.google.com/view/5vbJ5vildOq
PBR enabled:
```
 RendererConfiguration config = new RendererConfiguration();
        config.setShadowsEnabled(true);
        config.setBloomEnabled(true);
        config.setHDREnabled(true);
        config.setPBREnabled(true);

        mViroView = new ViroViewARCore(this, this, config);
```
When model is loaded :
```
   @Override
    public void onObject3DLoaded(Object3D object3D, Object3D.Type type) {
        Log.e("Stand", "onObject3DLoaded");
        final List<Material> materials = object3D.getMaterials();
        for (Material material : materials) {
            material.setMetalness(0.6f);
            material.setRoughness(0.1f);
            material.setLightingModel(Material.LightingModel.PHYSICALLY_BASED);
            material.setTransparencyMode(Material.TransparencyMode.RGB_ZERO);
        }
    }
```
Environment:
```
   Texture environment = Texture.loadRadianceHDRTexture(Helper.getUri(ASSET_PATH));
        mArScene.setLightingEnvironment(environment);
        mArScene.setBackgroundTexture(environment);
```
Result:
![1521215122671](https://user-images.githubusercontent.com/15327844/37530288-de3504f2-2941-11e8-8cb4-569af8820079.png)
Something wrong with material? Any help will be appreciated!

**Comment by dthian** [comment]
Hi @jacobwyn, do you have a screen shot on how the stand model from the asset.zip should look like?

I've attempted to loaded the model in an online viewer for verification and it looks similar to the screen shot you have posted - a mostly transparent table. 

<img width="824" alt="screen shot 2018-03-16 at 11 55 16 am" src="https://user-images.githubusercontent.com/1904934/37539476-0c6b05dc-2911-11e8-8f63-3ed43dbcc954.png">

Thanks!

**Comment by dthian** [comment]
Here is another screen shot from the side - this looks very very similar to the screen shot above - is this expected?

<img width="826" alt="screen shot 2018-03-16 at 11 58 34 am" src="https://user-images.githubusercontent.com/1904934/37539626-71479a10-2911-11e8-9553-8655915fadce.png">

**Comment by jacobwyn** [comment]
The stand model should be transparent, the material simulates a glass.

**Comment by dthian** [comment]
Thanks @jacobwyn, can you please provide a screenshot of you are expecting to see?

**Comment by dthian** [comment]
Also, can you explain what you meant by '50% of the cases'? By 50%, do you mean 50% of the times you have loaded this particular model, or did you mean instead 50% of the total number of models that you have?

Finally, are you trying to load up refractive materials mainly? Currently ViroCore does not support rendering refractive materials at the moment, i've filed story on the backlog for this feature request.

**Comment by jacobwyn** [comment]
Hi @dthian 
When I created this issue I didn't prepared enough and had hurried with the result, so PBR works well with OBJ models... mainly ... but not with those two stand and piano ... let me explain in details.
I'm trying to achieve such behaviour for glass material
https://www.dropbox.com/s/kslrrdkzvaumzdg/204266800858148.mp4?dl=0
![1521451277565](https://user-images.githubusercontent.com/15327844/37587692-b2ebf692-2b68-11e8-8b42-989a8fe9feae.png)
   marked spots  are reflected lights source from image I have loaded so
```
   Texture environment = Texture.loadRadianceHDRTexture(Helper.getUri(ASSET_PATH));
        mArScene.setLightingEnvironment(environment);
        mArScene.setBackgroundTexture(environment);
```
So when I say  PBR, I mean this behaviour of material, **sorry for previously confusing explanation and statements**

**Comment by dthian** [comment]
Thanks @jacobwyn, the reflected light sources from the lighting environment only works with PBR materials (as it requires Metal and Roughness properties to perform lighting and reflection calculations). We've taken a look at the Lamborghini model and it looks like it doesn't have any PBR materials (and thus, doesn't reflect HDR textures) - can you please confirm if this is true?

**Comment by jacobwyn** [comment]
Hi @dthian 

>  We've taken a look at the Lamborghini model and it looks like it doesn't have any PBR materials (and thus, doesn't reflect HDR textures) - can you please confirm if this is true?

PBR works good if I set manually all needed BPR staff on cars materials in onObject3DLoaded method. I don't have such problem with car's body.

The question is how to force custom model in my case the stands material to reflect  light sources from the lighting environment. 
Previously you said that there is some troubles with shader for glass material(sorry for oversimplification), and we need to avoid of using glass, picture below shows the same stand but without glass material 
![1521707981435](https://user-images.githubusercontent.com/15327844/37759803-6070387c-2dbd-11e8-9d27-fa1f1b351852.png)
It does not reflect   lights from the lighting environment, but it DOES reflect SpotLights that I added to the scene manually 
![1521708363438](https://user-images.githubusercontent.com/15327844/37760068-4050e8c4-2dbe-11e8-8ef8-9424d4af8652.png)

Therefore I have 2 question:
1. Why setting manually PBR (Metal and Roughness properties, enabling lighting mode PHYSICALLY_BASED)  stuff does not work always?  In one view we see, that it works for car but does not work for stand (stand model [stand.zip](https://github.com/viromedia/virocore/files/1836762/stand.zip))
2. After updating to 1.4.1 I have some problems with onClick listener, I did not get click events from models (from coloured buttons, see last pic.... all objects on stand are separated models ). I have suspicions it caused due to bounding box of each separate model

**Comment by jacobwyn** [comment]
Hey guys, still waiting for you advice.

**Comment by VikAdvani** [comment]
Hi @jacobwyn, 
We are looking into #2 now. 
Our designer is looking at 1 and 3. Will get back to you shortly.

**Comment by saboteur111** [comment]
Hi @jacobwyn 
1)I took a look and I believe the reason why the lambo displays in a more desirable manner is because its UV's have been laid out optimally. The stand was not laid out optimally:
![screen shot 2018-03-27 at 10 25 09 am](https://user-images.githubusercontent.com/23560993/37988494-e853ebfc-31b5-11e8-875b-d7500b29c6f6.png)
You could see some principles of UV unwrapping here: http://www.republicofcode.com/tutorials/3ds/unwrap_uvw_mapping/

I unwrapped and laid out the UV's in an optimal layout. You can see the difference here:
![screen shot 2018-03-27 at 11 26 28 am](https://user-images.githubusercontent.com/23560993/37988535-fe92bc86-31b5-11e8-9030-74539e81fac7.png)

Also, if you can, it's a good idea to use a PBR app like Substance Painter to create PBR materials to easily create textures and get more expected results. I attached a PBR-enabled stand for you:
[stand_pbr.zip](https://github.com/viromedia/virocore/files/1853382/stand_pbr.zip)

Here's the lambo w/ black glass as well:
[aventador_opaque.fbx.zip](https://github.com/viromedia/virocore/files/1853385/aventador_opaque.fbx.zip)

Hope this helps!

**Comment by achuvm** [comment]
@jacobwyn,

Adding a click listener on your provided `stand.obj` model works, however, we don't have the models for your buttons.

Your suspicion about the bounding box of the stand potentially interfering with the click detection on the buttons is probably correct. You can try using [`setIngoreEventHandling`](https://developer.viromedia.com/virocore/reference/com/viro/core/Node.html#setIgnoreEventHandling(boolean)) to true in order to disable event handling on your stand in the hopes that the buttons then don't get their events eaten by the stand. Your buttons look small enough that they shouldn't interfere with each other.

Let us know if this works for you. If not, feel free to send us your positioning code + assets and we can dive in deeper.

**Comment by jacobwyn** [comment]
Thank you very much guys!!!
I noticed that  I am loosing ability to get click events if I put stand closer than 2.5 m to car, setting  `setIngoreEventHandling` on a car - unfortunately  does not help (just put stand near car and try to click on stand)... we need to pay attention on bounding box of surroundings models while propagating such events... in my case is not vital.
About cars glass material - noticed that it does not reflect  light sources from the lighting environment  - I set all needed staff mentioned in the start of this thread, a question is pretty simple -why ?
Once again - thank you for the help!

**Comment by dthian** [comment]
> About cars glass material - noticed that it does not reflect light sources from the lighting environment - I set all needed staff mentioned in the start of this thread, a question is pretty simple -why?
Hey @jacobwyn, again, as previously mentioned above, how reflective an object is depends on the [PBR values](https://virocore.viromedia.com/docs/physically-based-rendering#materials) that you have set for that material. As shown in my example above, I've set the metal and roughness of the car's body metal, so as to achieve the shiny reflective look. As such, you would have to do the same for the material that you have set for your car's windows (should be named with a string containing "Glass"). 

> I noticed that I am loosing ability to get click events if I put stand closer than 2.5 m to car, setting setIgnoreEventHandling on a car - unfortunately does not help (just put stand near car and try to click on stand).
This sounds like the ignoreEventHandling bug that is fixed in the latest ViroCore 1.5 build. Previously, only the root node of the 3D model would have the ignoreHandling property applied, and as such the child nodes of the 3D object would still catch events (bug). However, this should be fixed in the latest release. To upgrade, please follow our upgrade guidance [here](https://virocore.viromedia.com/docs/releases). 

I've also attempted reproducing by placing the pbr stand very near the car (closer than 2.5m) as shown below, and am unable to reproduce the bug (I am able to click on the stand). I've demonstrated this by setting a click listener on the stand, that when clicked, rotates the car (as shown below). Also as seen, the windows of the car is reflecting the environment as desired as well. 

![ezgif-5-18e064d959](https://user-images.githubusercontent.com/1904934/38120034-cf6d5b70-337a-11e8-9a7d-0b0b04a5f832.gif)

**Comment by jacobwyn** [comment]
Hi @dthian , thanks for response! 
Bug with click events near big models  is really fixed in version 1.5, thanks!
Still cannot force cars glass material to reflect lighting environment, I have set PBR values - unfortunately it doesn't help

**Comment by saboteur111** [comment]
Hi @jacobwyn. I think the easiest solution is tho convert the textures to PBR formatting rather than setting the values through code, so I did the conversion for you. Here's the FBX w/ textures embedded. Run it through the VRX tool and ignore the .DDS files it exports. You should be able to gain transparency through the windows and headlights as well with this format:
![screen shot 2018-04-04 at 5 40 50 pm](https://user-images.githubusercontent.com/23560993/38341905-debd774a-382f-11e8-8769-62408903af5d.png)

[aventador_pbr.fbx.zip](https://github.com/viromedia/virocore/files/1878249/aventador_pbr.fbx.zip)

**Comment by jacobwyn** [comment]
Hi @saboteur111 
This model does not rendered, model is always transparent ... which is not surprising because there is a glass' shader bug ...have already reported in another thread 
Anyway, thanks for efforts!

**Comment by saboteur111** [comment]
hey @jacobwyn. It seems something happened when I exported to FBX from Maya. I re-exported the model and it should work now. I included the VRX file for you as well.
[lambo.zip](https://github.com/viromedia/virocore/files/1881743/lambo.zip)

**Comment by jacobwyn** [comment]
Hi @saboteur111, this model is rendered very well! Thanks a lot!
But need to report one more bug, after launching 5-10 times application (launch, put some 3d models, press back, repeat few times) I ma getting next erorr
```
04-06 10:42:57.072 16549-17330 E/Adreno-GSL: <gsl_memory_alloc_pure:2202>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
04-06 10:42:57.328 16549-17330 W/Adreno-GSL: <sharedmem_gpuobj_alloc:2318>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
```
And app is stuck, can reproduce it even in ARRetail

**Comment by dthian** [comment]
Hey @jacobwyn, could you also please update https://github.com/viromedia/virocore/issues/73 with the crash stack trace that you see when re launching the app 5-10 times? Thanks!
